# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dd9cb554e587b50cbfd7055c74d239f04b3dbb0ad0d451a20ef129a9599607976dafe8add81370eabc6de0a7fc8c9def419458ca980055cfbb09373502c162f5

test:
  secret_key_base: 7b92ad0012a739d15f4f12bd95dfb0a01184695ed547293cd3388c5999e615015615341cf79c8e081ee2d8f9d4f14713f79e9e67f027e92bcee76f8793e46bb5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
